"""Core layer — pure business & data logic, no Qt widgets.

UI and the Flask server both import from here so rules stay single-sourced.
"""
from eva_restaurant.core.database import (  # noqa: F401
    BASE_DIR,
    DATA_DIR,
    DB_PATH,
    LOCKED_STATUSES,
    LOG_DIR,
    OPEN_STATUSES,
    SETTINGS_PATH,
    UPLOAD_DIR,
    AppSettings,
    Base,
    ErrorLog,
    Food,
    Order,
    SessionLocal,
    checkpoint_wal,
    clear_errors,
    data_version,
    delete_food_image,
    engine,
    estimate_prep_minutes,
    find_open_order,
    get_or_create_api_key,
    get_session,
    hash_password,
    is_locked,
    load_settings,
    log_error,
    now_iso,
    parse_items,
    recent_errors,
    regenerate_api_key,
    sales_report,
    sales_report_range,
    save_settings,
    verify_password,
)
